### ISSUE TITLE
Latest release missing from ansible-galaxy

### ISSUE THREAD

**Issue by dvessey-fes** [dokku/ansible-dokku#159]
> If you're using Dokku - especially for commercial purposes - consider donating to project development via [OpenCollective](https://opencollective.com/dokku) or [Patreon](https://www.patreon.com/dokku). Funds go to general development, support, and infrastructure costs.
>
> If you'd like to sponsor specific functionality, see the project's [Sponsoring](https://github.com/dokku/.github/blob/master/SPONSORING.md) document.
>
> If you need support for a version of Dokku that is more than a year old, your issue may be closed without an answer. Please upgrade to a recent version before filing an issue.

## Description of problem

Latest version for ansible-dokku on ansible-galaxy is v2022.10.17 https://galaxy.ansible.com/dokku_bot/ansible_dokku - but latest release https://github.com/dokku/ansible-dokku/releases [v2022.12.19](https://github.com/dokku/ansible-dokku/releases/tag/v2022.12.19)

Not sure if this is intended or a token expired somewhere?

Thanks!

**Comment by ltalirz** [comment]
Thanks to @niicck for fixing CI; just pushed another tag - let's see whether it works now https://github.com/dokku/ansible-dokku/actions/runs/6771491839

**Comment by ltalirz** [comment]
Unfortunately, now the github action that deploys uploads the role to ansible galaxy is broken because the new ansible galaxy release is broken https://github.com/robertdebock/galaxy-action/issues/12

A fix [has been merged but not released](https://github.com/ansible/galaxy_ng/pull/1925)

**Comment by josegonzalez** [comment]
The fix has been released :)

**Comment by ltalirz** [comment]
Just re-pushed https://github.com/dokku/ansible-dokku/actions/runs/7958081917 - let's see whether it runs through

**Comment by ltalirz** [comment]
Unfortunately still getting
```
+ ansible-galaxy role import --api-key *** --branch master dokku ansible-dokku
ERROR! Error when finding available api versions from default (https://galaxy.ansible.com/) (HTTP Code: 403, Message: Forbidden)
```

If someone knows a working github action to publish galaxy roles, please open a PR

**Comment by ltalirz** [comment]
P.S. The action we're currently using is using a docker image; it's possible that the ansible galaxy version in there is outdated

**Comment by josegonzalez** [comment]
That image is this: https://github.com/robertdebock/docker-github-action-galaxy

Not sure what package in there needs to be updated, but maybe we can pull that image and validate that?

**Comment by nerg4l** [comment]
GitHub action link: https://github.com/robertdebock/galaxy-action
DockerHub link to the image: https://hub.docker.com/r/robertdebock/github-action-galaxy/tags

```
ansible-galaxy [core 2.16.2]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.12/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-galaxy
  python version = 3.12.1 (main, Dec  9 2023, 00:54:56) [GCC 13.2.1 20231014] (/usr/local/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

But the Docker image is irrelevant because the previously linked issue was on the server side.

There was some activity on ansible/galaxy#1980. Could this solve the error https://github.com/ansible/galaxy/issues/1980#issuecomment-1789702529 ?

**Comment by ltalirz** [comment]
> There was some activity on [ansible/galaxy#1980](https://github.com/ansible/galaxy/issues/1980). Could this solve the error [ansible/galaxy#1980 (comment)](https://github.com/ansible/galaxy/issues/1980#issuecomment-1789702529) ?

That's probably worth a try.

@josegonzalez Can you please create a new token at https://galaxy.ansible.com/ui/token/ and then try to `ansible-galaxy role import dokku ansible-dokku --token <token>`?

I tried it as well but I'm still getting a 403 (unfortunately they completely removed the UI on galaxy.ansible.com for looking at one's own collections, i.e. I don't see whether I have access to the ansible-dokku role on ansible galaxy or not).

If that works, please update the `GALAXY_API_KEY` on 
https://github.com/dokku/ansible-dokku/settings/secrets/actions

**Comment by josegonzalez** [comment]
I updated the token just now from the `dokku-bot` github user. Whats next?

**Comment by ltalirz** [comment]
Great, that did the trick!

I just re-ran the workflow https://github.com/dokku/ansible-dokku/actions/runs/7958081917 that previously failed - completes now.

New release is online https://galaxy.ansible.com/ui/standalone/roles/dokku_bot/ansible_dokku/versions/
